accessibility_tool:
  color_background_1: '#FFFFFF'
  color_foreground_1: '0000FF'
  color_background_2: '#333333'
  color_foreground_2: '#FFFFFF'
  color_background_3: '#000000'
  color_foreground_3: '#FFFFFF'
